// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO71vH7_zyz7VlDcZC8oi1g19LGSEVFFA',
    appId: '1:76792019370:web:0fd4ef95b75bb019b253d3',
    messagingSenderId: '76792019370',
    projectId: 'avnet-assessment',
    authDomain: 'avnet-assessment.firebaseapp.com',
    storageBucket: 'avnet-assessment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7xTHfjW0ErZ2TT-6unk579HIMUXI1AjI',
    appId: '1:76792019370:android:84cab1f09c11a065b253d3',
    messagingSenderId: '76792019370',
    projectId: 'avnet-assessment',
    storageBucket: 'avnet-assessment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdSZ1kRJOvf7c_RXJrdLgIFLcP4klDCPg',
    appId: '1:76792019370:ios:fea685a12171ce90b253d3',
    messagingSenderId: '76792019370',
    projectId: 'avnet-assessment',
    storageBucket: 'avnet-assessment.appspot.com',
    iosBundleId: 'com.example.auvnetInternshipAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdSZ1kRJOvf7c_RXJrdLgIFLcP4klDCPg',
    appId: '1:76792019370:ios:fea685a12171ce90b253d3',
    messagingSenderId: '76792019370',
    projectId: 'avnet-assessment',
    storageBucket: 'avnet-assessment.appspot.com',
    iosBundleId: 'com.example.auvnetInternshipAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO71vH7_zyz7VlDcZC8oi1g19LGSEVFFA',
    appId: '1:76792019370:web:c36fdcf7fa95c074b253d3',
    messagingSenderId: '76792019370',
    projectId: 'avnet-assessment',
    authDomain: 'avnet-assessment.firebaseapp.com',
    storageBucket: 'avnet-assessment.appspot.com',
  );

}